# -*- coding: utf-8 -*-
"""TFX_Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wz5Rf1eKfUVgLzHoAJFReX9BrcFzWWoK
"""

!pip install -U tfx

import os
import tempfile
import urllib
import tensorflow_transform as tft
import pandas as pd
import tensorflow as tf

_data_root = tempfile.mkdtemp(prefix='tfx-data')
DATA_PATH = 'https://raw.githubusercontent.com/tensorflow/tfx/master/tfx/examples/chicago_taxi_pipeline/data/simple/data.csv'
_data_filepath = os.path.join(_data_root, "data.csv")
urllib.request.urlretrieve(DATA_PATH, _data_filepath)

df = pd.read_csv(DATA_PATH)
print(df.columns)

CATEGORICAL_FEATURE_KEYS = [
    'payment_type',
    'company'
]

NUMERIC_FEATURE_KEYS = [
  'pickup_community_area', 'fare', 'trip_start_month', 
  'trip_start_hour','trip_start_day', 'trip_start_timestamp', 'pickup_latitude',
  'pickup_longitude', 'dropoff_latitude', 'dropoff_longitude', 'trip_miles', 
  'pickup_census_tract', 'dropoff_census_tract', 'trip_seconds', 'dropoff_community_area','tips'
  ]

def preprocessing_fn(inputs):
  outputs = inputs.copy()
  
  # normalization
  for key in NUMERIC_FEATURE_KEYS:
    outputs[key] = tft.scale_to_0_1(inputs[key])
  
  # categorical columns one-hot-encoding
  for key in CATEGORICAL_FEATURE_KEYS:
    outputs[key] = tft.compute_and_apply_vocabulary(
        tf.strings.strip(inputs[key]),
        # num_oov_buckets=1,
        vocab_filename=key)
  return outputs

